# Nome do nosso workflow
name: CI Backend


on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  build-e-testar-backend:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - name: Checkout do código
        uses: actions/checkout@v4

      
      - name: Setup do Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      
      - name: Instalar dependências do Back-end

      - name: Rodar Linter para Qualidade do Código
        run: |
          cd MERN-Stack-Todo-List-App-master/backend
          npm run lint


        run: |
          cd MERN-Stack-Todo-List-App-master/backend
          npm install

      # 4º Passo: Roda os testes automatizados
      - name: Rodar os testes
        
        run: |
         cd MERN-Stack-Todo-List-App-master/backend
         npm test -- --forceExit
        env:
          NODE_OPTIONS: --openssl-legacy-provider
