# Nome do nosso workflow
name: CI Backend


on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  build-e-testar-backend:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - name: Checkout do código
        uses: actions/checkout@v4

      
      - name: Setup do Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      
      - name: Instalar dependências do Back-end

      - name: Rodar Linter para Qualidade do Código
        run: |
          cd MERN-Stack-Todo-List-App-master/backend
          npm run lint


        run: |
          cd MERN-Stack-Todo-List-App-master/backend
          npm install

      # 4º Passo: Roda os testes automatizados
      - name: Rodar os testes
        
        run: |
         cd MERN-Stack-Todo-List-App-master/backend
         npm test -- --forceExit
        env:
          NODE_OPTIONS: --openssl-legacy-provider

          - name: Notificar Sucesso no Discord
            # Roda apenas se todos os passos anteriores deram certo
            if: success()
            uses: rjstone/discord-webhook-notify@v1
            with:
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
              description: "✅ Sucesso! O pipeline do branch `${{ github.ref_name }}` foi concluído com sucesso."
              color: "3066993" # Cor Azul

          - name: Notificar Falha no Discord
            # Roda apenas se algum passo anterior falhou
            if: failure()
            uses: rjstone/discord-webhook-notify@v1
            with:
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
              description: "❌ FALHA! O pipeline do branch `${{ github.ref_name }}` falhou. Verifique os logs no GitHub."
              color: "15158332" # Cor Vermelha
